#!/usr/bin/env python3
"""TTF 子集 -> VLW(LovyanGFX 8-bit alpha 抗锯齿字体)-> C 头数组。

VLW 格式(全 32-bit big-endian,源码核实自 TFT_eSPI/LovyanGFX):
  头:glyphCount, version(11), fontSize(px), mboxY(0), ascent(px), descent(px)
  每字形(unicode 升序):unicode, height, width, xAdvance, gdY(bitmap_top), gdX(bitmap_left), pad
  位图:所有 metric 之后连续,每字形 w*h 字节 0-255 alpha,无 pitch 填充。
用法:gen_vlw.py <ttf> <size_px> <out.h> <array_name> [--text STR | --ascii]
"""
import argparse
import struct
import sys

import freetype


def _i32(v):
    return struct.pack(">i", int(v))


def render_vlw(ttf_path, codepoints, size_px, face_index=0):
    face = freetype.Face(ttf_path, index=face_index)
    face.set_pixel_sizes(0, size_px)
    cps = sorted(set(int(c) for c in codepoints))   # 升序去重(LovyanGFX 硬性要求)
    glyphs, max_a, max_d = [], 0, 0
    for cp in cps:
        face.load_char(cp, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
        g = face.glyph
        bmp = g.bitmap
        w, h, pitch, src = bmp.width, bmp.rows, bmp.pitch, bmp.buffer
        pix = bytearray(w * h)
        for row in range(h):
            base = row * pitch
            pix[row * w:row * w + w] = bytes(src[base:base + w])
        glyphs.append({"u": cp & 0xFFFF, "h": h, "w": w,
                       "adv": g.advance.x >> 6, "dy": g.bitmap_top, "dx": g.bitmap_left,
                       "bmp": bytes(pix)})
        max_a = max(max_a, g.bitmap_top)
        max_d = max(max_d, h - g.bitmap_top)
    out = bytearray()
    out += _i32(len(glyphs)) + _i32(11) + _i32(size_px) + _i32(0) + _i32(max_a) + _i32(max_d)
    for g in glyphs:
        out += _i32(g["u"]) + _i32(g["h"]) + _i32(g["w"]) + _i32(g["adv"]) + _i32(g["dy"]) + _i32(g["dx"]) + _i32(0)
    for g in glyphs:
        out += g["bmp"]
    return bytes(out), glyphs


def parse_vlw_check(data, glyphs):
    """逆向校验:头/metric/bitmap 终点与升序,失败抛 AssertionError。"""
    gc = struct.unpack(">i", data[0:4])[0]
    assert gc == len(glyphs), "glyphCount mismatch"
    off = 24
    us = []
    total_bmp = 0
    for _ in range(gc):
        u, h, w = struct.unpack(">iii", data[off:off + 12])
        us.append(u)
        total_bmp += w * h
        off += 28
    assert us == sorted(us), "glyphs not ascending"
    assert off + total_bmp == len(data), "bitmap region size mismatch"


def to_header(data, name):
    lines = ["#pragma once", "// generated by scripts/gen_vlw.py — do not edit",
             f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        lines.append("  " + ",".join(str(b) for b in data[i:i + 16]) + ",")
    lines.append("};")
    lines.append(f"static const unsigned long {name}_len = {len(data)};")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ttf")
    ap.add_argument("size", type=int)
    ap.add_argument("out")
    ap.add_argument("name")
    ap.add_argument("--text", default="")
    ap.add_argument("--ascii", action="store_true")
    ap.add_argument("--face-index", type=int, default=0)
    a = ap.parse_args()
    cps = set()
    if a.ascii:
        cps |= set(range(0x20, 0x7F))        # 可打印 ASCII
        cps |= {0x00B7, 0x2026}              # · 中点(行2分隔) 与 … 省略号
    cps |= {ord(c) for c in a.text}
    if not cps:
        print("no codepoints (use --ascii or --text)", file=sys.stderr)
        sys.exit(2)
    data, glyphs = render_vlw(a.ttf, cps, a.size, a.face_index)
    parse_vlw_check(data, glyphs)            # 自检
    with open(a.out, "w") as f:
        f.write(to_header(data, a.name))
    print(f"{a.out}: {len(glyphs)} glyphs, {len(data)} bytes -> {a.name}")


if __name__ == "__main__":
    main()
